# Generated by Django 5.1.1 on 2024-12-19 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie', '0002_alter_customuser_cod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=255)),
                ('descriere', models.TextField()),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicatie.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Promotie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=255)),
                ('data_creare', models.DateTimeField(auto_now_add=True)),
                ('data_expirare', models.DateTimeField()),
                ('subiect', models.CharField(max_length=255)),
                ('mesaj', models.TextField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cod_promotie', models.CharField(max_length=100, unique=True)),
                ('categorii', models.ManyToManyField(to='aplicatie.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Vizualizare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vizualizare', models.DateTimeField(auto_now_add=True)),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicatie.produs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicatie.customuser')),
            ],
            options={
                'ordering': ['-data_vizualizare'],
            },
        ),
    ]
