# Generated by Django 5.1.1 on 2025-01-02 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie', '0003_produs_promotie_vizualizare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vizualizare',
            name='produs',
        ),
        migrations.AddField(
            model_name='vizualizare',
            name='instrument',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='aplicatie.instrument'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='vizualizare',
            table='aplicatie_vizualizari',
        ),
        migrations.DeleteModel(
            name='Produs',
        ),
    ]
