# Generated by Django 5.1.1 on 2025-01-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie', '0004_remove_vizualizare_produs_vizualizare_instrument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blocat',
            field=models.BooleanField(default=False),
        ),
    ]
