# Generated by Django 5.1.1 on 2024-10-31 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_exemplu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prajitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=50, unique=True)),
                ('descriere', models.TextField(blank=True, null=True)),
                ('pret', models.DecimalField(decimal_places=2, max_digits=8)),
                ('gramaj', models.IntegerField()),
                ('tip_produs', models.CharField(default='cofetarie', max_length=50)),
                ('calorii', models.IntegerField()),
                ('categorie', models.CharField(default='comuna', max_length=50)),
                ('pt_diabetici', models.BooleanField(default=False)),
                ('imagine', models.CharField(blank=True, max_length=300, null=True)),
                ('data_adaugare', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
